import Head from "next/head";
import GlobalStyle from "../styles/styledGlobal";
import { Header } from "../components/Header";
import { HomePage } from "../components/Home";
import { Features } from "../components/Features";
import { Product } from "../components/Product";
import { CardDeal } from "../components/CardDeal";
import { Clients } from "../components/Clients";
import { CTA } from "../components/CTA";
import { Footer } from "../components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Hoobank</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalStyle />
      <Header />
      <HomePage />
      <Features />
      <Product />
      <CardDeal />
      <Clients />
      <CTA />
      <Footer />
    </>
  );
}
